server:
  port: 8000
  servlet:
    context-path: /

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    jackson:
      serialization:
        fail-on-empty-beans: false